name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}
          
      - name: Generate Docker Image Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/liatrio/hello-world-dotnet
          tags: |
            type=sha
          flavor: |
            latest=auto

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./hello-world-dotnet
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
